name: EAS Update

on:
    push:
        branches:
            - main

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install EAS CLI
              run: npm install -g eas-cli

            - name: Install Expo CLI
              run: npm install -g expo-cli

            - name: Log in to Expo
              env:
                  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
              run: expo login --token $EXPO_TOKEN

            - name: Install dependencies
              run: npm install

            - name: Create an update
              run: eas update --branch main
